name: Fetch latest dnsmasq changes

on:
  schedule:
    - cron: '0 0 * * 1'  # This will run at 00:00 UTC every Monday
  workflow_dispatch:  # This allows the workflow to be manually triggered

jobs:
  fetch-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Git Configurations
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Fetch latest changes
      run: |
        git remote add dnsmasq git://thekelleys.org.uk/dnsmasq.git
        git fetch dnsmasq
        git fetch dnsmasq 'refs/tags/*:refs/tags/*'
        git fetch dnsmasq '+refs/heads/*:refs/remotes/dnsmasq/*'
        git checkout main
        git merge --allow-unrelated-histories dnsmasq/master

    - name: Commit and push changes
      run: |
        if ! git diff --quiet; then
          git add -A
          git commit -m "Update from dnsmasq repository"
          git push origin main
        else
          echo "No changes"
        fi